[package]
name    = "forgebike-domain"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror   = { workspace = true }
serde       = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
